### ISSUE TITLE
Salesforce Bulk Delete, Error: "Unable to delete" while successful

### ISSUE THREAD

**Issue by ebspeter** [bcolas/PDISforceBulkPlugin#29]
The new bulk delete step works but still reports an Error for me.

java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

![image](https://user-images.githubusercontent.com/15634297/47701891-e48f7700-dc4d-11e8-8af1-c876d3df8be8.png)

```
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Unexpected error
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - Unable to delete
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - 
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - 	at org.pentaho.di.trans.steps.sforcebulkdelete.SalesforceBulkDelete.checkResults(SalesforceBulkDelete.java:188)
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - 	at org.pentaho.di.trans.steps.sforcebulkdelete.SalesforceBulkDelete.executeBatch(SalesforceBulkDelete.java:144)
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - 	at org.pentaho.di.trans.steps.sforcebulkdelete.SalesforceBulkDelete.processRow(SalesforceBulkDelete.java:55)
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/10/30 13:56:27 - Salesforce Bulk Delete.0 - 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bcolas** [comment]
Issue found
Plugin was sending null lines : Fixed !
